### PR TITLE
Remove literal

### PR DESCRIPTION
**Pull request by smulube**
This PR contains the changes I needed to make to get the skill running using UK English as a language where use of `AMAZON.LITERAL` has been removed.

It:

* adds a sample custom slot type `NAMES`
* removes the `AMAZON.LITERAL` references from `intents.json`
* updates utterances.txt to remove now unused entries
* updates README to reference the new custom slot type
* changes the links in the readme to point back to @rgraciano's fork

I have tested the deployed skill and I think it is working for me.

### CODE REVIEW

**Comment by philhawthorne** [comment]
Used the code in this to get the my integration working!

Thank you!

**Comment by smulube** [comment]
Hi Phil,

that's great, glad it worked for someone else.

On Sat, 10 Dec 2016, 12:38 Phil Hawthorne, <notifications@github.com> wrote:

Used the code in this to get the my integration working!

Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rgraciano/echo-sonos/pull/85#issuecomment-266204957>,
or mute the thread

**Comment by l0cutis** [comment]
Excellent work :) Also in the UK and the lack of support for AMAZON.LITERAL was scuppering me too! Interestingly, I had similar grief getting custom code to work on Samsung's SmartThings platform on their EU servers... I don't understand why US/UK platforms don't have feature parity?

Still :) your efforts are appreciated - it certainly works for me!

**Comment by rgraciano** [comment]
This is great - thanks for the update, and for cleaning up those name constants

**Comment by shaneewels** [comment]
Help please still cant get this to work for me.

**Comment by shaneewels** [comment]
Finally got it going.

**Pull request merged**
