### PR TITLE
Greatly enhanced Apple Music capability

### PR DESCRIPTION
**Pull request by jplourde5**
With enhanced functionality that has just been published to sonos-http-api, you now have native Echo-like song playing capabilities for Apple Music.  Added capabilities for:

1. Queue and play up to 50 of the most popular tracks for an artist name
2. Play a song title
3. Play a combination of artist name and song title
4. Play an Apple Music Radio station based on an artist name, song title, or combination of artist name and song title
5. Queue and play of to 50 of the most popular tracks for the artist that is currently playing
6. Start playing a radio station based on the current artist and song title that is playing

### CODE REVIEW

**Comment by rgraciano** [comment]
Great - I'm looking forward to this functionality myself.  It looks like you removed the "preset" syntax, though?  We'll have to furnish a replacement (maybe something like "run preset") and document that, since it's historically been the primary use case

**Comment by jplourde5** [comment]
Sounds good. It conflicted directly with the simplicity of being able to say "Play SONG/AUTHOR in ROOM" .  I was actually just trying to remove the Play intent and didn't think about Play PRESET.  I like your idea about redoing it as "Play preset PRESET".  Will you put it back in or would you like me to?

**Comment by jplourde5** [comment]
I'm putting the Play preset in now...

**Comment by jplourde5** [comment]
I have added it back.  The only difference from the earlier version is the utterance.  You now say "Play preset PRESET".

**Comment by rgraciano** [comment]
I like this feature a lot, but it's only available for those who have Apple Music.  It seems a shame to effectively disable the "play" utterance for everyone who does not use Apple Music.  

I suggest a minor change to make it friendlier for everyone:

1) Keep "play preset PRESET"
2) Change "play" to only use Apple Music if an option is set in options.js.  Maybe something like "musicservice = 'apple'".  Default would be false.  Opens the door to adding 'spotify' and other services later.  I'm imagining this is basically an if->then in index.js' PlayIntent.  If the option is 'apple' then use apple; otherwise default to using a preset, calling the same function that "play preset PRESET" would call.

**Comment by jplourde5** [comment]
Hi Ryan,

I like your idea to have an option to point to a user’s preferred default music service.  One question though, the PRESETS have a defined slot while the “music” services have to use the LITERAL in order to accommodate the millions of potential tracks and artists.  How would the option handle a change in the utterance?  I suppose that the preset could switch to a LITTERAL too, but I think that you might lose some accuracy.   Understand that the iTunes search uses a fuzzy search so the Alexa interpretation just has to be close, not exact.  The defined slot search is supposed to work in a similar fashion but I found that the accuracy dropped off significantly without the predefined presets.

Maybe the way to handle it is keep play “preset” PRESET, but have the configurable option (Apple, Spotify, etc., Presets) use the LITTERAL slot instead of the PRESETS slot.  If you are willing to incorporate fuse.js (https://github.com/krisk/Fuse ), then it will always find the best match.  This is what I’ve done with the SiriusXM functionality in Jimmy’s node-sonos-http-api solution (beta) to find the right channel name and/or number.  It works very well.


BTW,
I have the solution updated for the new beta node-sonos-http-api being worked on that is almost complete.  I’ve added support for SiriusXM and I’m finishing up Pandora now.


[cid:image001.gif@01D1C591.E0D3C600]<http://www.infor.com/>

Jim Plourde | VP Cloud Services
mobile: 864.270.7677 | office: 864.546.5089 | jim.plourde@infor.com<mailto:jim.plourde@infor.com> | http://www.infor.com<http://www.infor.com/>

**Comment by jplourde5** [comment]
After thinking about it, since "play {preset}" has no room and the presets are well defined, I don't think that this will collide with the Music intents.  I still like your "options" idea for being able to integrate other music services with the same Music intents.

**Comment by ryansmiller** [comment]
Hey guys,

I'm super interested in this feature (about to get an Echo Dot as we speak). As an avid Apple Music and Sonos user, this feature closes the loop for home music automation for me.

If there is anything you need to help moving this forward (code, testing, whatever), let me know. Happy to help!

**Comment by jplourde5** [comment]
You can use this to test if you like.  The master branch works with the master branch of node-sones-http-api and the beta branch works with the beta branch of n-s-h-a

**Comment by fsosa** [comment]
I'd love to add Spotify integration. It looks like I'd need to add Spotify searching on node-sonos-http-api, and then add the Echo functionality here. Would people be interested in this?

**Comment by jplourde5** [comment]
Just answered your post on jishi's project. I've created a new service called musicSearch that extends what I did for appleMusic to Spotify and I will add others. I'll then enhance what I did here to add a Config setting that will allow someone to choose which service to use for the same intents that now only support Apple Music.

**Comment by jplourde5** [comment]
I meant to add that I already have Spotify working in the new service.  As I indicated in jishi's project, I'll submit it when I get back around the 7th.

**Comment by jplourde5** [comment]
musicSearch now supports Apple Music, Spotify, and Deezer.  A pull request has been submitted on the beta branch of node-sones-http-api and it is already available on my beta branch.  I'm working on the echo-sonos functionality now.  A new musicService setting in options.js will allow you to specify which music service to use.  The default is Apple Music.  I'll submit a pull request here once I finish testing the echo-sonos changes.

**Comment by rgraciano** [comment]
@jplourde5 - sounds great. Looking forward to trying it out

**Comment by jplourde5** [comment]
I'll submit it as soon as it gets pushed into node-so is-http-api.

**Comment by jratliff681** [comment]
@jplourde5 I'm looking over the code for this. How hard would it be to add musicSearch support for the queue or Sonos music library? I have a network hdd with ~2000 mp3s on it. Using the node-sonos-http-api you can use http://localhost:5005/living room/queue/[start-index]/[count] to get the queue in json. This gives you the song file uri and names. I noticed if you only use the /queue it only gives the first 500 songs. If you request start index 0 and count of 2000 it still only gives you the first 1000 songs.  I was going to play around with grabbing the first 1000 then requesting the second 1000 and add them together, then use the fuzzy search to find the song and get the uri to send to Sonos to play.

I'll start playing with it as I have time. I figured I'd mention it to you as well since you already know how this works and it might be simple for you to add in. Thanks for all the work on the new additions!

**Comment by jplourde5** [comment]
Already working on it.

**Comment by NeilRShah** [comment]
I just wanted you to know that I'm very excited about this. I just installed my new Sonos system, have an echo and use Apple Music, and would love to link it all together. I was so excited when I saw this. 

Thanks for all your (and rgraciano's) work!

**Comment by gijoecool** [comment]
I wanted to set this up this weekend at my house. If I understand this correctly, then I should use jplourde5/echo-sonos/beta (not rgraciano/echo-sonos)? Are there plans to merge these changes to rgraciano/echo-sonos?

**Comment by jplourde5** [comment]
Correct.  I got everything working last night.  I want to do a little more testing once I wind down from my day job ;).  I'll then create releases for both of my branches, node-sones-http-api-beta and echo-sones, and post the links (which you can probably figure out anyway).

**Comment by gijoecool** [comment]
@jplourde5 - Awesome! Thank you for all your hard work!

**Comment by Connor-Knabe** [comment]
@jplourde5 thanks so much for doing this!  Can you let us know when this is pulled in? I attempted to get it working but it seems like the beta (from your fork) version of n-s-h-a doesn't understand the musicsearch action route.

**Comment by jplourde5** [comment]
You have to use my distributions for now while it is being tested. The nsha is built on jishi's beta branch which is working well. Echo-Sonos is built on the main branch and I'm shooting for the default behavior to be the same as the original.

**Comment by pjkottke** [comment]
Is there any current/planned functionality for playing artists from Amazon Music?

Currently, is it just through "favorites" or "playlists"?

**Comment by jplourde5** [comment]
I should be able to add it fairly easily.  Are you using this with the Echo?  If so, we are testing the echo-side now.  The node-sones-http-api side is solid.  We are still working on some utterance tuning for the echo.  It is working great for me and another tester. Two others are having problems with consistency that we are trying to figure out now.

**Comment by pjkottke** [comment]
I would be using it with Echo. I have not yet over to your fork; it is currently setup with the rgraciano build.

**Comment by jplourde5** [comment]
Great.  Let us finish working through the echo-sonos testing and it should be easy to add Prime support.

**Comment by jplourde5** [comment]
pjkottke, looking for a public music search api for Amazon Music and I'm coming up empty. I can't add support without a search api.  Let me know if you can find one and I'll take a look.

**Comment by pjkottke** [comment]
I'll take a look, but after a brief search it doesn't look good. I may have misunderstood the current end-goal of the project. I was hoping to be able to speak the name of an artist I have in my personal Amazon library. Is the current implementation for streaming services only (Apple Music, Spotify, etc.)? Maybe I just need to get a Spotify account again...

**Comment by jplourde5** [comment]
musicSearch supports Apple Music, Spotify, Deezer, and the Sonos local music library. Other services can be added but there has to be a public api for searching for the music.

**Comment by gijoecool** [comment]
Switching the skill trigger from Sonos to sonos fixed it for me too!

Now I have a new request... Is it possible to automatically shuffle the music played? For example, if you say "alexa ask sonos to play artist the rolling stones", then on Apple Music you will always hear Gimme Shelter first. Doing the same natively on Echo will usually start with a different song each request.

**Comment by jplourde5** [comment]
I've kicked the thought around a few times, but didn't do it because there are already commands for shuffle mode and repeat. Another challenge is that you may get the same first song regardless, because I purposely don't wait for the entire queue to be loaded before playing. The other thing to note if you turn shuffle on is that you will always want repeat on also because the first song playing gets pushed down into the queue as the other tracks load and the songs added above will not play unless repeat is on.  This all mainly comes about because Sonos now loads the queue in random order instead of playing the queue in random order like it used to do.

Thoughts?

**Pull request closed without merging**
