### PR TITLE
Shortcuts and room turn up down

### PR DESCRIPTION
**Pull request by kevnull**
- added: keywords “party”, “lounge”, “chill”
- added: turn (room name) up|down

### CODE REVIEW

**Comment by kevnull** [comment]
Oops. Wasn't really meaning this to merge to yours…but there are definitely elements you may want.

**Comment by rgraciano** [comment]
Would love to merge Next/Prev & State into master, as they were on my list of future additions.  If you're interested in contributing, please drop the custom intents and the app id, and we should be mostly good to go.

Volume also looks good, and a future enhancement could be to change relative volume by a value (eg "increase volume by 10" or "add 10 to volume") rather than setting to an absolute.

**Comment by pwakeford** [comment]
I was also going to do the current state enhancement this weekends, thanks for saving me some time and agreed it would be great to see in the main branch,

**Comment by rgraciano** [comment]
@kevnull, LMK if you plan to do this, or if one of us should add it to our todo list.  Thanks!

**Comment by kevnull** [comment]
@rgraciano I somehow never saw this and then was traveling for a few months. Did you end up getting these features in?

**Comment by rgraciano** [comment]
A bunch of similar changes have been added since then. Take a look at the
newest version and we can circle back if there are gaps

**Pull request closed without merging**
