### PR TITLE
Pandora Support

### PR DESCRIPTION
**Pull request by jplourde5**
Added the Pandora utterances now that the api has the Pandora support

### CODE REVIEW

**Comment by rgraciano** [comment]
@jplourde5 - can you fix the conflicts and then I'll merge? guessing this is README-related

**Comment by agelastic** [comment]
It doesn't look like this request merged in the end :(

**Comment by jplourde5** [comment]
Are you sure?  I thought that it had been merged.

**Comment by jplourde5** [comment]
Never mind. I see now that it has not. I'll take a look.

**Comment by jplourde5** [comment]
rgraciano, 
I'm not seeing what the conflicts are.  I'll be happy to resolve if you can point me to what they are.

agelastic,
In the mean time, all that you need to do is copy the additional utterances from the pull request and insert them into your own Alexa utterances.  That is the only real change.  The code for Pandora support was already in there.

**Comment by agelastic** [comment]
@jplourde5 No worries, I've set it up a while ago, plus modified utterances - e.g. added "shut up" 😆 
Just wanted to remind you guys that this is quite useful functionality.

**Comment by rgraciano** [comment]
I resolved the minor README conflict and merged.  Thanks!

**Pull request merged**
