### PR TITLE
Make options read environment variables

### PR DESCRIPTION
**Pull request by npwalker**
Prior to this commit, users needed to copy options.example.js
into place as options.js and hand edit it.

After this commit, users need not hand edit the options.js file
as all of the customization they want to do to the options can be
supplied by environment variables in lambda.

### CODE REVIEW

**Comment by bensymonds** [comment]
This looks good to me!

**Comment by rgraciano** [comment]
Thanks for the submission! I agree this is a better way to do things, but it nukes backward compatibility - a git pull breaks stuff without significant user action.

A better way to do it would be "if options.js exists, use that.  else, use these environment variables", and note in options.example.js that using that file is no longer the preferred way to set your options

**Comment by npwalker** [comment]
@rgraciano I figured a `git pull` would cause a merge conflict and users could decide what to do from there.  

However, I can certainly change this back to being the .example file and add the step back into the README that says to copy it over?

**Comment by rgraciano** [comment]
@npwalker, there are a lot of people using the project who aren't experienced with git or even with any sort of source control, so it'd be preferable to keep it easy for them.

So, yeah - it'd be better to keep it as .example, and then in the README, keep the instruction to copy the .example file (but also note that if they prefer, they can set environment variables instead, per a link to some instructions on how to do that.)

**Comment by jhmartin** [comment]
+1 for environmental variables; much easier to update a variable than re-package if you need to change your dynamic hostname.  However it should be backwards compatible.

**Comment by npwalker** [comment]
@rgraciano okay, I updated this PR to leave options.example.js and instruct users to copy it into place as before.

**Comment by rgraciano** [comment]
@npwalker - awesome.  thanks!

**Pull request merged**
